config/routes.rb
NorexBlog::Application.routes.draw do
  get 'tags/:tag', to: 'tumbles#index', as: :tag

  get 'posts/recent(.:format)', to: 'tumbles#recent', defaults: { format: 'json' }
  get 'posts/:id' => 'tumbles#show', :as => :tumble
  get 'search' => 'tumbles#search', :as => :search

  root :to => 'tumbles#index'

  

end

app/models/tumble.rb
class Tumble < ActiveRecord::Base
  extend FriendlyId

  attr_accessible :content, :content_type, :date, :title, :tumblr_id, :url, :tag_list

  belongs_to :user

  acts_as_taggable
  friendly_id :title, use: :slugged

  acts_as_indexed :fields => [:title, :content]

  def self.get_by_tags(params)
    tags = params[:tags] || nil

    if tags.nil?
      where('1 = 1')
    else
      tagged_with(tags, any: true)
    end
  end

  def self.get_by_types(params)
    types = params[:types] || nil
    if types.nil?
      where('1 = 1')
    else
      where(content_type: types)
    end
  end

  def self.get_by_users(params)
    users = params[:users] || nil
    if users.nil?
      where('1 = 1')
    else
      where(user_id: users)
    end
  end

  def self.fetch_new
    client = Tumblr::Client.new do |config|
      config.consumer_key = ENV['TUMBLR_CONSUMER_KEY']
      config.consumer_secret =  ENV['TUMBLR_CONSUMER_SECRET']
      config.oauth_token = ENV['TUMBLR_OAUTH_TOKEN']
      config.oauth_token_secret = ENV['TUMBLR_OAUTH_TOKEN_SECRET']
    end

    posts = get_posts_from_tumblr(client)
    
    posts['response']['posts'].each do |post|
      attributes = get_attributes(post)

      if attributes
        user_name = post.blog_name
        user = User.where(name: user_name).first_or_create

        blog_info = client.blog_info(user_name + '.tumblr.com')['response']['blog']
        avatar = client.avatar(user_name + '.tumblr.com', size: 64)['response']
       
        user.update_attributes(blog_name: blog_info.title, photo: avatar.avatar_url, description: blog_info.description)
        new_tumble = user.tumbles.create(attributes.merge(content_type: post.type, date: post.date, tumblr_id: post.id))
        new_tumble.tag_list = post.tags
        new_tumble.save
      end
    end
  end

  def self.get_posts_from_tumblr(client)
    since = Tumble.order("tumblr_id DESC").select("tumblr_id").first
    posts = since ? client.dashboard(since_id: since.tumblr_id.to_s) : client.dashboard
  end

  def self.get_attributes(tumble)
    attributes = { title: '', content: '', url: ''}

    case tumble.type
    when 'text', 'chat'
      attributes.merge!({ title: Sanitize.clean(tumble.title), content: tumble.body })
    when 'quote'
      attributes.merge!({ title: Sanitize.clean(tumble.source), content: tumble.text })
    when 'link'
      attributes.merge!({ title: Sanitize.clean(tumble.title), content: tumble.description, url: tumble.url })
    when 'video'
      attributes.merge!({ title: Sanitize.clean(tumble.caption), content: tumble.player.last.embed_code })
    when 'audio'
      attributes.merge!({ title: Sanitize.clean(tumble.caption), content: tumble.player })
    when 'photo'
      attributes.merge!({ title: Sanitize.clean(tumble.caption), content: tumble.photos.to_yaml })
    else
      attributes = nil
    end

    attributes
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :blog_name, :description, :name, :photo

  has_many :tumbles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tumbles_controller.rb
class TumblesController < ApplicationController
  def index
    # @tumbles = Tumble.get_by_types(params).get_by_tags(params).get_by_users(params).order('date DESC').page(params['page'] || 1).per(2)
    @tumbles = Tumble.order('date DESC').page(params['page'] || 1).per(5)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @tumble = Tumble.find(params[:id])
    @next_tumble = Tumble.where('date < ?', @tumble.date).order('date DESC').first
    @prev_tumble = Tumble.where('date > ?', @tumble.date).order('date ASC').first
  end

  def search
    @query = params[:query].downcase

    unless @query.blank?
      #@tumbles = Tumble.where('title LIKE ?', "%#{@query}%").get_by_types(params).get_by_tags(params).order('date DESC')
      #@@tumbles = Tumble.where('title LIKE ?', "%#{@query}%").order('date DESC')
      @tumbles = Tumble.find_with_index(@query)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def recent
    tumble = Tumble.where('content_type != "photo"').order('date DESC').first
    result = { title: tumble.title, content: tumble.content, url: tumble_url(tumble) }

    respond_to do |format|
      format.html { render json: result }
      format.json { render json: result }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def in_action(action)
    params[:action].downcase == action.to_s.downcase
  end

  def tag_link_to(tag, count)
    current_tags = get_current_tags(tag)
    #params[:action] = 'index'
    
    link_to raw("#{tag} (#{count}) <span class='light'>&nbsp;</span>"), params.merge({:"tags" => current_tags.any? ? current_tags : ['none']}), class: (current_tags.include?(tag) ? '' : 'active')
  end

  def type_link_to(type, type_plural, out)
    type = type.to_s
    current_types = get_current_types(type)
    
    link_to raw("<span class='entypo #{type_plural.to_s}'>&nbsp;</span>"), params.merge({:"types" => current_types.any? ? current_types : ['none']}), class: type_link_to_classes(!current_types.include?(type), out)
  end

  def user_link_to(user)
    user = user.to_s
    current_users = get_current_users(user)
   
    link_to raw("<span class='#{(current_users.include?(user) ? '' : 'on')}'>&nbsp;</span>"), params.merge({:"users" => current_users.any? ? current_users : ['none']}), class: 'switch'
  end

  def type_link_to_classes(active, out)
    classes = []
    classes << 'active' if active
    classes << 'out' if out

    classes.join ' '
  end

  def get_current_tags(tag)
    current_tags = params[:tags].try(:dup) || nil
    all_tags = Tumble.tag_counts.map { |tag| tag.name }

    if current_tags.nil?
      current_tags = all_tags.reject { |t| t == tag } 
    else
      if current_tags.include? tag
        current_tags = current_tags.reject { |t| t == tag } 
      else
        current_tags = (current_tags << tag)
      end

      current_tags = current_tags.reject { |t| t == 'none' } 
    end

    current_tags
  end

  def get_current_types(type)
    type = type.to_s

    current_types = params[:types].try(:dup) || nil
    all_types = %w{photo video text misc}

    if current_types.nil?
      current_types = all_types.reject { |t| t == type } 
    else
      if current_types.include? type
        current_types = current_types.reject { |t| t == type } 
      else
        current_types = (current_types << type)
      end

      current_types = current_types.reject { |t| t == 'none' } 
    end

    current_types
  end

  def get_current_users(user)
    current_users = params[:users].try(:dup) || nil
    all_users = User.all.map { |user| user.id.to_s }

    if current_users.nil?
      current_users = all_users.reject { |u| u == user }
    else
      puts 'NOT IN NIL'
      if current_users.include? user
        current_users = current_users.reject { |u| u == user } 
      else
        current_users = (current_users << user)
      end

      current_users = current_users.reject { |u| u == 'none' } 
    end

    current_users
  end

end

app/helpers/tumbles_helper.rb
module TumblesHelper
  def format_date(date, format)
    unless date.nil?
      date.strftime(format)
    end
  end

  def random_colour
    ['blue', 'orange', 'pink', 'green'].sample
  end

  def tumble_link(tumble)
    link_to strip_tags(tumble.title), (tumble.url || tumble_path(tumble))
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def first_name(name)
    name.blank? ? "" : name.split(" ")[0]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title><%= (yield(:title) + " | " unless yield(:title).blank?).to_s + "Norex Blog" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta property="og:title" content="<%= yield(:title) %>" />
  <meta property="og:description" content="<%= yield(:description) %>" />
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=113486685521739";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <div id="super-container">
    <%= render 'shared/sidebar' %>
    <%# debug(params) %>
    <aside id="main-content">
      <%= render 'shared/loader' %>
      <div id="posts">
        <%= yield %>
      </div>
    </aside>
  </div>
</body>
</html>

app/views/shared/_authors_block.html.erb
<div class="block authors">
  <h2>Authors <a href="#">all</a></h2>
  <div class="divider dark">&nbsp;</div>
  <ul id="author-list">
    <li class="active">
      <a href="#" class="avatar"><span class="shadow">&nbsp;</span><img src="/images/author-justin.png" alt="Justin Bellefontaine"></a>
      <h5>Justin</h5>
      <h6>Designer</h6>
      <a href="#" class="switch"><span class="on">&nbsp;</span></a>
    </li>
    <li>
      <a href="#" class="avatar"><span class="shadow">&nbsp;</span><img src="/images/author-justin.png" alt="Justin Bellefontaine"></a>
      <h5>Justin</h5>
      <h6>Designer</h6>
      <a href="#" class="switch"><span class="on">&nbsp;</span></a>
    </li>
    <li>
      <a href="#" class="avatar"><span class="shadow">&nbsp;</span><img src="/images/author-justin.png" alt="Justin Bellefontaine"></a>
      <h5>Justin</h5>
      <h6>Designer</h6>
      <a href="#" class="switch"><span class="on">&nbsp;</span></a>
    </li>
    <li>
      <a href="#" class="avatar"><span class="shadow">&nbsp;</span><img src="/images/author-justin.png" alt="Justin Bellefontaine"></a>
      <h5>Justin</h5>
      <h6>Designer</h6>
      <a href="#" class="switch"><span class="on">&nbsp;</span></a>
    </li>
  </ul>
</div>

app/views/shared/_loader.html.erb
<article id="post-loader" class="post-loader hidden">
  <%= image_tag('loader.gif') %>
</article>

app/views/shared/_sidebar.html.erb
<section id="main-sidebar"> 
  <div class="container">
    <div class="block" id="main-nav">
      <ul>
        <li><%= link_to 'About', 'http://sitebynorex.com/about' %></li>
        <li><%= link_to 'Work', 'http://sitebynorex.com/work' %></li>
        <li><%= link_to 'Sitebynorex.com', 'http://sitebynorex.com/', class: 'orange' %></li>
        <li><%= link_to '@sitebynorex', 'http://twitter.com/sitebynorex', class: 'twitter' %></li>
      </ul>
      <a href="#main-nav" id="main-nav-btn" class="menu-icon"><span class="entypo">&#9776;</span></a>
    </div>
    <div class="block center">
      <a href="/"><%= image_tag('logo.png', alt: 'The Society of Online Engineers') %></a>
    </div>
    <div class="block search">
      <%= form_tag search_path, :method => 'get' do %>
        <p>
          <%= text_field_tag 'query', nil, :placeholder => 'Search' %>
        </p>
      <% end %>
    </div>
    <% if params[:action] == 'index' %>
      <%#= render 'shared/types_block' %>
      <%#= render 'shared/tags_block' %>
      <%#= render 'users/sidebar_block' %>
    <% end %>
  </div>
</section>

app/views/shared/_tags_block.html.erb
<%#= @tag_list ||= Tumble.tag_counts %>
<div id="tags-block" class="block categories">
  <h2>Tags</h2>
  <div class="divider dark">&nbsp;</div>
  <ul id="category-list">
    <% Tumble.tag_counts.each do |tag| %>
    <% puts tag %>
      <li><%= tag_link_to(tag.name, tag.count) %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_types_block.html.erb
<div class="block types">
  <div id="type-knob">
    <ul id="types-list" class="circles">
      <%= render 'shared/types_block_links' %>
    </ul>
    <a href="#" id="centerbutton">
      <span class="light">&nbsp;</span>
      <h6>Post Types</h6>
    </a>
  </div>
</div>

app/views/shared/_types_block_links.html.erb
<% out ||= false %>
<% { photo: :photos, video: :videos, text: :text, misc: :misc }.each do |singular, plural| %>
  <li><%= type_link_to(singular, plural, out) %></li>  
<% end %>

app/views/tumbles/_tumble.html.erb
<article class="<%= random_colour %> <%= tumble.content_type %>">
  <%= render tumble.user %>
  <section>
    <header>
      <h1><%= tumble_link(tumble) %></h1>
      <h6>by <%= tumble.user.blog_name %> | <%= format_date(tumble.date, '%B %d, %Y') %></h6>
    </header>
    <% if tumble.content_type == 'photo' %>
      <p><%= image_tag(YAML::load(tumble.content)[0]["original_size"].url) %>
    <% else %>
      <p class="content-container"><%= raw tumble.content %></p>
    <% end %>
    <ul class="tags">
      <% tumble.tag_list.each do |tag| %>
        <li><span class="start"><em>&nbsp;</em></span><%= tag %><span class="end"><em>&nbsp;</em></span></li>
      <% end %>
    </ul>
    <% if in_action(:show) %>
      <ul class="share">
        <li>
          <div class="social-btns">
            <div class="fb-like" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
            <a href="https://twitter.com/share" class="twitter-share-button" data-via="sitebynorex" data-dnt="true">Tweet</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
          </div>
        <li><a href="#">Back to Top</a></li>
      </ul>
      <%= render partial: 'users/user_full', object: tumble.user, as: :user %>
      <ul class="pagination">
        <li><% if @prev_tumble %><%= link_to raw('&laquo; Older Post'), @prev_tumble %><% end %></li>
        <li><% if @next_tumble %><%= link_to raw('Newer Post &raquo;'), @next_tumble %><% end %></li>
      </ul>
    <% end %>
  </section>
</article>

app/views/tumbles/_tumble_empty.html.erb
<article class="<%= random_colour %>">
  <aside class="post-type-author"></aside>
  <section>
    <header>
      <h1><a href="#">No posts are available</a></h1>
      <h6>Please check back later</h6>
    </header>
  </section>
</article>

app/views/tumbles/_tumbles.html.erb
<%= render(@tumbles) || render('tumbles/tumble_empty') %>

app/views/tumbles/index.html.erb
<%= render 'tumbles/tumbles' %>
<article class="pager-holder">
	<section>
		<ul class="pagination">
			<li><%= link_to_previous_page @tumbles, raw('&laquo; Newer Posts') %></li>
			<li><%= link_to_next_page @tumbles, raw('Older Posts &raquo;') %></li>
		</ul>
	</section>
</article>

app/views/tumbles/index.js.erb
$('#post-loader').addClass('hidden');
$("#posts").html("<%= j render('tumbles/tumbles') %>");
$("#tags-block").replaceWith("<%= j render('shared/tags_block') %>");
$("#types-list").html("<%= j render('shared/types_block_links', out: true) %>");
$("#author-list").html("<%= j render(partial: 'users/user_sidebar', collection: User.all, :as => :user) %>");

app/views/tumbles/search.html.erb
<% content_for :title, "Search: #{@query}" %>

<%= render 'tumbles/tumbles' %>

app/views/tumbles/search.js.erb
$('#post-loader').addClass('hidden');
$("#posts").html("<%= j render('tumbles/tumbles') %>");
$("#tags-block").replaceWith("<%= j render('shared/tags_block') %>");
$("#types-list").html("<%= j render('shared/types_block_links', out: true) %>");

app/views/tumbles/show.html.erb
<% content_for :title, @tumble.title %>
<% content_for :description, strip_tags(@tumble.content) if (@tumble.content_type != 'photo') %>

<%= render @tumble %>

app/views/users/_sidebar_block.html.erb
<div class="block authors">
  <h2>Authors</h2>
  <div class="divider dark">&nbsp;</div>
  <ul id="author-list">
    <%= render partial: 'users/user_sidebar', collection: User.all, :as => :user %>
  </ul>
</div>

app/views/users/_user.html.erb
<aside class="post-type-author">
  <ul>
    <li><a class="post-icon" href="#"><span class="entypo">&nbsp;</span></a></li>
    <li><span class="arrow left">&nbsp;</span></li>
    <li><a href="#" class="avatar"><%= image_tag user.photo, alt: user.blog_name, class: 'avatar' %></a></li>
  </ul>
</aside>

app/views/users/_user_full.html.erb
<section id="author-vcard">
  <%= image_tag user.photo, alt: user.blog_name %>
  <aside>
    <header>
      <h1><%= user.blog_name %></h1>
      <h3><%= user.description %></h3>
    </header>
  </aside>
</section><!--END AUTHOR VCARD-->

app/views/users/_user_sidebar.html.erb
<li class="active">
  <a href="#" class="avatar"><span class="shadow">&nbsp;</span><%= image_tag user.photo, alt: user.blog_name, class: 'avatar' %></a>
  <h5><%= first_name(user.blog_name) %></h5>
  <h6><%= user.description %></h6>
  <%= user_link_to(user.id) %>
  <!-- <a href="#" class="switch"><span class="on">&nbsp;</span></a> -->
</li>